#!/bin/bash

###
#    This file installs everything you need to run the ipynb. If you already have an environment to run it, just skip this and install the dependencies
#    If you are on a new computer you may need to restart terminal a few times and keep rerunning this file. 
#    Also it may need an executable mod with chmod +x install_tensorflow
###

sudo apt update
sudo apt install curl

if conda --version
 then
  echo "Miniconda already installed"
 else
  echo "INSTALLING MINICONDA"
  curl https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -o ~/Downloads/Miniconda3-latest-Linux-x86_64.sh
  bash ~/Downloads/Miniconda3-latest-Linux-x86_64.sh
fi
echo "setting auto_activate_base to false"
conda config --set auto_activate_base false

eval "$(conda shell.bash hook)"

conda create --name tf python=3.9
conda deactivate
conda activate tf

if nvidia-smi
 then
  echo "INSTALLING tf with GPU and CPU support"
  conda install -c conda-forge cudatoolkit=11.2 cudnn=8.1.0
  export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/
  #make that path extension permanent
  mkdir -p $CONDA_PREFIX/etc/conda/activate.d
  echo 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/' > $CONDA_PREFIX/etc/conda/activate.d/env_vars.sh
 else
  echo "***"
  echo "INSTALLING tf with CPU only, if you want gpu support cancel now Ctrl-C and go select an nvidia video card driver"
  echo "***"
fi

pip install --upgrade pip
pip install tensorflow

python3 -c "import tensorflow as tf; print('\n\nTensorFlow Installed!\ntest:\navailable devices:\n',tf.config.list_physical_devices())"

pip install -r requirements.txt

conda install jupyterlab

conda deactivate
echo "Now run 'conda activate tf' then run 'jupyter lab'"
